export const permissions_pt = {
    CREATE_EVENTS: "criar eventos",
    CREATE_GUILD_EXPRESSIONS: "criar expressões do servidor",
    USE_SOUNDBOARD: "usar painel de efeito sonoro",
    USE_EXTERNAL_SOUNDS: "usar painel de efeito sonoro externos",
    MANAGE_GUILD_EXPRESSIONS: "gerenciar expressões do servidor",
    MOVE_MEMBERS: "mover membros",
    CREATE_INSTANT_INVITE: "criar convites instantâneos",
    KICK_MEMBERS: "expulsar membros",
    BAN_MEMBERS: "banir membros",
    ADMINISTRATOR: "administrador",
    MANAGE_CHANNELS: "gerenciar canais",
    MANAGE_GUILD: "gerenciar servidor",
    ADD_REACTIONS: "adicionar reação",
    VIEW_AUDIT_LOG: "ver registro de auditoria",
    PRIORITY_SPEAKER: "voz prioritária",
    STREAM: "vídeo",
    VIEW_CHANNEL: "ver canais",
    SEND_MESSAGES: "enviar mensagens",
    SEND_TTS_MESSAGES: "enviar mensagens em texto-para-voz",
    MANAGE_MESSAGES: "gerenciar mensagens",
    EMBED_LINKS: "inserir links",
    ATTACH_FILES: "anexar arquivos",
    READ_MESSAGE_HISTORY: "ler histórico de mensagens",
    MENTION_EVERYONE: "mencionar todos",
    USE_EXTERNAL_EMOJIS: "usar emojis externos",
    VIEW_GUILD_INSIGHTS: "ver análises do servidor ",
    CONNECT: "conectar",
    SPEAK: "falar",
    MUTE_MEMBERS: "mutar membros",
    DEAFEN_MEMBERS: "ensurdecer membros",
    USE_VAD: "usar detecção de voz",
    CHANGE_NICKNAME: "alterar apelido",
    MANAGE_NICKNAMES: "gerenciar apelidos",
    MANAGE_ROLES: "gerenciar cargos",
    MANAGE_WEBHOOKS: "gerenciar webhooks",
    MANAGE_EMOJIS_AND_STICKERS: "gerenciar emojis e figurinhas",
    USE_APPLICATION_COMMANDS: "usar aplicativo de comandos",
    REQUEST_TO_SPEAK: "pedir para falar",
    MANAGE_EVENTS: "gerenciar eventos",
    MANAGE_THREADS: "gerenciar tópicos",
    CREATE_PUBLIC_THREADS: "criar tópicos públicos",
    CREATE_PRIVATE_THREADS: "criar tópicos privados",
    USE_EXTERNAL_STICKERS: "usar figurinhas externas",
    SEND_MESSAGES_IN_THREADS: "enviar mensagem em tópicos",
    USE_EMBEDDED_ACTIVITIES: "usar atividades integradas",
    MODERATE_MEMBERS: "moderar membros",
    VIEW_CREATOR_MONETIZATION_ANALYTICS: "ver analítica de monetizaçãodo criador"
}